# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push tests
# run-name: ${{ github.actor }} push tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.10.13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v17"
        with:
          default: "${{ matrix.python }}"
      - name: Setup Env
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -e .
      - name: test
        run: |
          python src/imio/updates/tests/tests.py
